<a href="https://colab.research.google.com/github/khojwar/Master_Thesis/blob/main/002_Nepali_pos_tagging_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# upload nnc_updated_ah folder

authenticate and mount the Google Drive

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
# Chage directory to project folder
%cd /content/drive/MyDrive/Nepali POS Tagging/
%ls

/content/drive/MyDrive/Nepali POS Tagging
002_Nepali_pos_tagging_SVM.ipynb  nnc_updated_ah/


`parse` is process of analyzing and interpreting the structured data within an XML document. When you "parse" an XML document, you are essentially ***breaking down its contents into meaningful parts and converting them into a format that a computer program can understand and work with***.

**The parse performs following tasks:**

1. Tokenization: The *XML document is divided into individual units* called tokens. These tokens include elements, attributes, text content, comments, and other XML constructs.

2. Validation: The parser *checks the document's structure against the rules* defined by the associated Document Type Definition (DTD) or XML Schema to ensure that it adheres to the specified format and rules.

3. Building a Data Structure: As the parser processes the XML document, it constructs an internal data structure (often a tree-like structure called the Document Object Model or DOM) that represents the hierarchical relationships between the different elements and their content.

4. Error Handling: If the parser *encounters any syntax errors or violations of the XML rules*, it generates error messages to indicate the issues in the document.

5. Extraction of Data: Once the XML document is successfully parsed, a program can then extract and manipulate the data within the document using the data structure created during the parsing process.

Parsing XML is a fundamental step when working with XML data in programming. It allows applications to ***extract information from XML documents, modify the data, and perform various operations based on the content contained within the XML structure***. Different programming languages and libraries provide XML parsing capabilities, enabling developers to work with XML data efficiently.

`ElementTree` represents the entire XML document and provides a way to navigate, manipulate, and extract data from the XML structure.

# 1. ParseXMLCorpus.py

The below code focused on parsing XML files, extracting specific data from them, and processing that data. The code appears to be dealing with linguistic annotations (tags) within XML elements.

`os.listdir()` retrieve a list of all files and directories present in a specified directory

In [3]:
import os
import xml.etree.ElementTree as ET    #It allows to create, modify, and extract information from XML documents using a simple and intuitive API.

# Set the path to the directory containing XML files
path = 'nnc_updated_ah/gc/books/'
filelist = os.listdir(path)

tags = []   # List to store extracted tags

# Loop through each XML file in the directory
for file in filelist:
    filepath = os.path.join(path, file)
    # print(filepath)

    tree = ET.parse(filepath)   # Parse an XML file and create an ElementTree object
    root = tree.getroot()   # Get the root element of the XML document

    for data in root.findall('text'):
        for value in data:
            # print(value.tag)

            # Check if the current 'value' has a tag 'group'
            if (value.tag == 'group'):
                # for group in value.findall('group'):
                for body in value.findall('body'):
                    for div in body.findall('div'):
                        for subdiv in div:
                            # print(subdiv.tag)

                            # Check if the current 'subdiv' has a tag 'head'
                            if (subdiv.tag == "head"):
                                for sentence in subdiv.findall('s'):
                                    # print(sentence.attrib)
                                    for s in sentence:
                                        # print(s.attrib)

                                        # Check if the current 's' has a tag 'foreign'
                                        if (s.tag == "foreign"):
                                            for words in s.findall('w'):
                                                tags.append(words.attrib['ctag'])
                                                print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                        # print("\n")

                                        # Check if the current 's' has a tag 'w'
                                        if (s.tag == "w"):
                                            tags.append(s.attrib['ctag'])
                                            print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                            # countTags(tags,s.attrib['ctag'])
                                    print('\n')

                            # Check if the current 'subdiv' has a tag 'p'
                            if (subdiv.tag == "p"):
                                for sentence in subdiv.findall('s'):
                                    print(sentence.attrib)
                                    for s in sentence:
                                        if (s.tag == "foreign"):
                                            for words in s.findall('w'):
                                                tags.append(words.attrib['ctag'])
                                                print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                                # countTags(tags,words.attrib['ctag'])
                                        # print("\n")
                                        if (s.tag == "w"):
                                            tags.append(s.attrib['ctag'])
                                            print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                            # countTags(tags,s.attrib['ctag'])
                                    print('\n')

            # Check if the current 'value' has a tag 'body'
            if (value.tag == 'body'):
                # for body in value.findall('body'):
                for div in value.findall('div'):
                    for subdiv in div:
                        # print(subdiv.tag)

                        # Check if the current 'subdiv' has a tag 'head'
                        if (subdiv.tag == "head"):
                            for sentence in subdiv.findall('s'):
                                print(sentence.attrib)
                                for s in sentence:
                                    # print(s.attrib)

                                    # Check if the current 's' has a tag 'foreign'
                                    if (s.tag == "foreign"):
                                        for words in s.findall('w'):
                                            tags.append(words.attrib['ctag'])
                                            print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # countTags(tags,words.attrib['ctag'])
                                    # print("\n")
                                    if (s.tag == "w"):
                                        tags.append(s.attrib['ctag'])
                                        print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                        # countTags(tags,s.attrib['ctag'])
                                print('\n')

                        # Check if the current 'subdiv' has a tag 'p'
                        if (subdiv.tag == "p"):
                            for sentence in subdiv.findall('s'):
                                print(sentence.attrib)
                                for s in sentence:
                                    if (s.tag == "foreign"):
                                        for words in s.findall('w'):
                                            tags.append(words.attrib['ctag'])
                                            print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # countTags(tags,words.attrib['ctag'])
                                    # print("\n")
                                    if (s.tag == "w"):
                                        tags.append(s.attrib['ctag'])
                                        print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                        # countTags(tags,s.attrib['ctag'])
                                print('\n')
#
# print(tags)
# output = set()
# for x in tags:
#     output.add(x)
# print("Number of tags:", len(output))
# print(output)


Streaming output truncated to the last 5000 lines.
प्रतिव्यक्ति/JX ६०/MM हजार/MM देखि/II एक/MM लाख/MM रूपैयाँ/NN सम्म/II लिएर/VQ गरिए/VE का/IKO यी/DDX अप्रेसन/NN हरू/IH सबै/JX असफल/JX भए/VE को/IKM कुरा/NN पीडित/JX हरू/IH ले/IE प्रहरी/NN लाई/IA बताए/VE का/IKO छन्/VVYX2 ।/YF 

{'n': '4650'}
पक्राउ/NN पर्नु/VI अघि/II सम्म/II पनि/TT राणा/NN रोगी/NN हरू/IH लाई/IA फसाउँदै/VDX थिए/VVYX2 ,/YM '/YQ अप्रेसन/NN गर्न/VI '/YQ ७०/MM हजार/MM रूपैयाँ/NN ठीक/JX पारेर/VQ डाक्टर/NN भेट्न/VI जाँदा/VDO उनी/DDX पक्राउ/NN परिसके/VE को/IKM थाहा/NN पाए/VE की/IKF सोफी/NP योञ्जन/NN भन्छिन्/VVYM1F ,/YM “/YQ कसो/DKX डुबिएनछ/VVYN1 !/YF ”/FS 

{'n': '4651'}
रोगी/NN हरू/IH प्रति/II निर्मम/JX भए/VE पनि/TT आफू/PRF लाई/IA हरेक/JX पाइला/NN मा/II संरक्षण/NN दिने/VN डा./FB भोजराज/NP जोशी/NP प्रति/II भने/TT उन/DDX को/IKM व्यवहार/NN मैत्रीपूर्ण/JX र/CC सहयोगी/JX देखिन्छ/VVYN1 ।/YF 

{'n': '4652'}
जुन/DJX दिन/NN उन/DDX ले/IE रत्न/NP थापा/NP को/IKM अप्रेसन/NN गरे/VE का/IKO थिए/VVYX2 ,/YM त्यसै/DDX दिन/NN ,/YM ४/MM जेठ/NN २०५६/

# (TRK)  Summerize the above code for easy understand

In [4]:
import os
import xml.etree.ElementTree as ET    #It allows to create, modify, and extract information from XML documents using a simple and intuitive API.


path = 'nnc_updated_ah/gc/books/'
filelist = os.listdir(path)

tags = []

for file in filelist:
    filepath = os.path.join(path, file)

    tree = ET.parse(filepath)
    root = tree.getroot()

    for data in root.findall("text"):     # used in Python in combination with regular expressions (regex) to extract all occurrences of a particular pattern in a given string("text").
        for value in data:

            for div in value.findall("div"):
                for subdiv in div:

                    for sentence in subdiv.findall("s"):
                        print(sentence.attrib)
                        for s in sentence:
                            # print(s.tag)
                            # print(s.attrib)
                            # print(s.attrib['ctag'])
                            tags.append(s.attrib['ctag'])
                            print(f"{s.text}/{s.attrib['ctag']}", '', end=''),
                        print('\n')




Streaming output truncated to the last 5000 lines.
प्रतिव्यक्ति/JX ६०/MM हजार/MM देखि/II एक/MM लाख/MM रूपैयाँ/NN सम्म/II लिएर/VQ गरिए/VE का/IKO यी/DDX अप्रेसन/NN हरू/IH सबै/JX असफल/JX भए/VE को/IKM कुरा/NN पीडित/JX हरू/IH ले/IE प्रहरी/NN लाई/IA बताए/VE का/IKO छन्/VVYX2 ।/YF 

{'n': '4650'}
पक्राउ/NN पर्नु/VI अघि/II सम्म/II पनि/TT राणा/NN रोगी/NN हरू/IH लाई/IA फसाउँदै/VDX थिए/VVYX2 ,/YM '/YQ अप्रेसन/NN गर्न/VI '/YQ ७०/MM हजार/MM रूपैयाँ/NN ठीक/JX पारेर/VQ डाक्टर/NN भेट्न/VI जाँदा/VDO उनी/DDX पक्राउ/NN परिसके/VE को/IKM थाहा/NN पाए/VE की/IKF सोफी/NP योञ्जन/NN भन्छिन्/VVYM1F ,/YM “/YQ कसो/DKX डुबिएनछ/VVYN1 !/YF ”/FS 

{'n': '4651'}
रोगी/NN हरू/IH प्रति/II निर्मम/JX भए/VE पनि/TT आफू/PRF लाई/IA हरेक/JX पाइला/NN मा/II संरक्षण/NN दिने/VN डा./FB भोजराज/NP जोशी/NP प्रति/II भने/TT उन/DDX को/IKM व्यवहार/NN मैत्रीपूर्ण/JX र/CC सहयोगी/JX देखिन्छ/VVYN1 ।/YF 

{'n': '4652'}
जुन/DJX दिन/NN उन/DDX ले/IE रत्न/NP थापा/NP को/IKM अप्रेसन/NN गरे/VE का/IKO थिए/VVYX2 ,/YM त्यसै/DDX दिन/NN ,/YM ४/MM जेठ/NN २०५६/

# 2. ExtractFeatures.py

The below code defines three functions, `get_features`, `get_wordFeatures`, and `get_testfeatures`, which ***generate feature dictionaries*** based on input tokens and an index.

In [5]:
# Function to get features for a given token index
def get_features(tokens, index):
    word = tokens[index]
    pos = tokens[index + 1]


    # Calculate previous and previous-previous words and parts-of-speech
    if index == 0:
        prevword = ''
        prevpos = ''
        prevprevword = ''
        prevprevpos = ''
    elif index == 2:
        prevword = tokens[index - 2]
        prevpos = tokens[index - 1]
        prevprevword = ''
        prevprevpos = ''
    else:
        prevword = tokens[index - 2]
        prevpos = tokens[index - 1]
        prevprevword = tokens[index - 4]
        prevprevpos = tokens[index - 3]

    # Calculate next and next-next words and parts-of-speech
    if index == len(tokens) - 2:
        nextword = ''
        nextpos = ''
        nextnextword = ''
        nextnextpos = ''
    elif index == len(tokens) - 4:
        nextword = tokens[index + 2]
        nextpos = tokens[index + 3]
        nextnextword = ''
        nextnextpos = ''
    else:
        nextword = tokens[index + 2]
        nextpos = tokens[index + 3]
        nextnextword = tokens[index + 4]
        nextnextpos = tokens[index + 5]

    # Construct and return the feature dictionary
    features = {'feature': {'word': word, 'pos': pos, 'next-word': nextword, 'next-pos': nextpos,
                            'next-next-word': nextnextword,
                            'next-next-pos': nextnextpos, 'prev-word': prevword, 'prev-pos': prevpos,
                            'prev-prev-word': prevprevword,
                            'prev-prev-pos': prevprevpos}, 'pos': pos}


    return {
        'word': word,
        'pos': pos,

        'next-word': nextword,
        'next-pos': nextpos,

        'next-next-word': nextnextword,
        'nextnextpos': nextnextpos,

        'prev-word': prevword,
        'prev-pos': prevpos,

        'prev-prev-word': prevprevword,
        'prev-prev-pos': prevprevpos,

    }


# Function to get word features for a given token index
def get_wordFeatures(tokens, index):
    word = tokens[index]
    # pos = tokens[index + 1]

    # Calculate previous and previous-previous words
    if index == 0:
        prevword = ''
        prevprevword = ''
    elif index == 1:
        prevword = tokens[index - 1]
        prevprevword = ''
    else:
        prevword = tokens[index - 1]
        prevprevword = tokens[index - 2]


    # Calculate next and next-next words
    if index == len(tokens) - 1:
        nextword = ''
        nextnextword = ''

    elif index == len(tokens) - 2:
        nextword = tokens[index + 1]
        nextnextword = ''

    else:
        nextword = tokens[index + 1]
        nextnextword = tokens[index + 2]

# return the word feature dictionary
    return {
        'word': word,
        # 'pos': '',

        'next-word': nextword,
        # 'next-pos': '',

        'next-next-word': nextnextword,
        # 'nextnextpos': '',

        'prev-word': prevword,
        # 'prev-pos': '',

        'prev-prev-word': prevprevword,
        # 'prev-prev-pos': '',
    }

# Function to get test features for a given token index
def get_testfeatures(tokens, index):
    word = tokens[index]

    # Calculate previous and previous-previous words
    if index == 0:
        prevword = ''
        prevprevword = ''

    elif index == 2:
        prevword = tokens[index - 2]
        prevprevword = ''

    else:
        prevword = tokens[index - 2]
        prevprevword = tokens[index - 4]

    # Calculate next and next-next words
    if index == len(tokens) - 2:
        nextword = ''
        nextnextword = ''

    elif index == len(tokens) - 4:
        nextword = tokens[index + 2]
        nextnextword = ''
    else:
        nextword = tokens[index + 2]
        nextnextword = tokens[index + 4]

    # Construct and return the test feature dictionary
    return {
        'word': word,
        # 'pos': '',

        'next-word': nextword,
        # 'next-pos': '',

        'next-next-word': nextnextword,
        # 'nextnextpos': '',

        'prev-word': prevword,
        # 'prev-pos': '',

        'prev-prev-word': prevprevword,
        # 'prev-prev-pos': '',

    }


These functions generate dictionaries containing different combinations of word, part-of-speech, and context information for a given token index within a list of tokens. The specific features extracted depend on the function and the index provided as input.

# (TRK) summerize the above code

In [14]:
def get_features(tokens, index):
    word = tokens[index]
    pos = tokens[index + 1]

    prevword = ''
    prevpos = ''
    prevprevword = ''
    prevprevpos = ''

    nextword = ''
    nextpos = ''
    nextnextword = ''
    nextnextpos = ''

    # Calculate previous and previous-previous words and parts-of-speech
    if index >= 2:
        prevword = tokens[index - 2]
        prevpos = tokens[index - 1]
        if index >= 4:
            prevprevword = tokens[index - 4]
            prevprevpos = tokens[index - 3]

    # Calculate next and next-next words and parts-of-speech
    if index <= len(tokens) - 4:
        nextword = tokens[index + 2]
        nextpos = tokens[index + 3]
        if index <= len(tokens) - 6:
            nextnextword = tokens[index + 4]
            nextnextpos = tokens[index + 5]

    return {
        'prev-prev-word': prevprevword,
        'prev-prev-pos': prevprevpos,

        'prev-word': prevword,
        'prev-pos': prevpos,

        'word': word,
        'pos': pos,

        'next-word': nextword,
        'next-pos': nextpos,

        'next-next-word': nextnextword,
        'next-next-pos': nextnextpos,
    }


def get_wordFeatures(tokens, index):
    word = tokens[index]

    # Calculate previous and previous-previous words
    if index == 0:
        prevword = ''
        prevprevword = ''
    elif index == 1:
        prevword = tokens[index - 1]
        prevprevword = ''
    else:
        prevword = tokens[index - 1]
        prevprevword = tokens[index - 2]

    # Calculate next and next-next words
    if index == len(tokens) - 1:
        nextword = ''
        nextnextword = ''
    elif index == len(tokens) - 2:
        nextword = tokens[index + 1]
        nextnextword = ''
    else:
        nextword = tokens[index + 1]
        nextnextword = tokens[index + 2]

    # Return the word feature dictionary
    return {
        'prev-prev-word': prevprevword,
        'prev-word': prevword,
        'word': word,
        'next-word': nextword,
        'next-next-word': nextnextword,
    }



def get_testfeatures(tokens, index):
    word = tokens[index]

    prevword = ''
    prevprevword = ''

    nextword = ''
    nextnextword = ''

    # Calculate previous and previous-previous words
    if index >= 2:
        prevword = tokens[index - 2]
        if index >= 4:
            prevprevword = tokens[index - 4]

    # Calculate next and next-next words
    if index <= len(tokens) - 4:
        nextword = tokens[index + 2]
        if index <= len(tokens) - 6:
            nextnextword = tokens[index + 4]

    # Return the test feature dictionary
    return {
        'prev-prev-word': prevprevword,
        'prev-word': prevword,
        'word': word,
        'next-word': nextword,
        'next-next-word': nextnextword,
    }


# 3. getFeatures.py

* Converting word features into Numpy arrays
* Converting test word features into Numpy arrays
* Support vectors
* No of Support Vectors
* Support vector indices


In [6]:
# -*- coding: utf-8 -*-
import os
# import ExtractFeatures    # Assuming this module contains functions for feature extraction
import xml.etree.ElementTree as ET
# from sklearn.feature_extraction import DictVectorizer
# from sklearn.svm import LinearSVC
# from sklearn.svm import SVC
# from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction import DictVectorizer
from sklearn import svm

path = 'nnc_updated_ah\\cs\\a07.xml'    # Set the path to a specific XML file
# filelist = os.listdir(path)
# for file in filelist:
#     filepath = os.path.join(path, file)
#     print(filepath)

X, y, X_test, y_test, test_sen, train_sen = [], [], [], [], [], []    # Lists to store training data (features and labels) and test data (features)
temp = 0

# Sample training data (features) and labels
# List of feature dictionaries
trainFeatures = [{'prev-word': '', 'next-word': 'निर्वाचन', 'word': 'आम'}, {'prev-word': 'आम', 'next-word': 'मा', 'word': 'निर्वाचन'}, {'prev-word': 'निर्वाचन', 'next-word': 'स्पष्ट', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'बहुमत', 'word': 'स्पष्ट'}, {'prev-word': 'स्पष्ट', 'next-word': 'ल्याए', 'word': 'बहुमत'}, {'prev-word': 'बहुमत', 'next-word': 'को', 'word': 'ल्याए'}, {'prev-word': 'ल्याए', 'next-word': 'नेपाली', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'काँग्रेस', 'word': 'नेपाली'}, {'prev-word': 'नेपाली', 'next-word': 'को', 'word': 'काँग्रेस'}, {'prev-word': 'काँग्रेस', 'next-word': 'संसदीय', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'दल', 'word': 'संसदीय'}, {'prev-word': 'संसदीय', 'next-word': 'का', 'word': 'दल'}, {'prev-word': 'दल', 'next-word': 'नेता', 'word': 'का'}, {'prev-word': 'का', 'next-word': 'को', 'word': 'नेता'}, {'prev-word': 'नेता', 'next-word': 'रुप', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'मा', 'word': 'रुप'}, {'prev-word': 'रुप', 'next-word': 'श्री', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'गिरीजा', 'word': 'श्री'}, {'prev-word': 'श्री', 'next-word': 'प्रसाद', 'word': 'गिरीजा'}, {'prev-word': 'गिरीजा', 'next-word': 'कोइराला', 'word': 'प्रसाद'}, {'prev-word': 'प्रसाद', 'next-word': 'ले', 'word': 'कोइराला'}, {'prev-word': 'कोइराला', 'next-word': 'पन्द्रह', 'word': 'ले'}, {'prev-word': 'ले', 'next-word': 'सदस्यीय', 'word': 'पन्द्रह'}, {'prev-word': 'पन्द्रह', 'next-word': 'मन्त्रि', 'word': 'सदस्यीय'}, {'prev-word': 'सदस्यीय', 'next-word': 'परिषद', 'word': 'मन्त्रि'}, {'prev-word': 'मन्त्रि', 'next-word': 'को', 'word': 'परिषद'}, {'prev-word': 'परिषद', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'गरी', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'सक्नु', 'word': 'गरी'}, {'prev-word': 'गरी', 'next-word': 'भए', 'word': 'सक्नु'}, {'prev-word': 'सक्नु', 'next-word': 'पछि', 'word': 'भए'}, {'prev-word': 'भए', 'next-word': 'मुलुक', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'को', 'word': 'मुलुक'}, {'prev-word': 'मुलुक', 'next-word': 'ध्यान', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'राष्ट्रिय', 'word': 'ध्यान'}, {'prev-word': 'ध्यान', 'next-word': 'सभा', 'word': 'राष्ट्रिय'}, {'prev-word': 'राष्ट्रिय', 'next-word': 'को', 'word': 'सभा'}, {'prev-word': 'सभा', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'र', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'त्यस', 'word': 'र'}, {'prev-word': 'र', 'next-word': 'पछि', 'word': 'त्यस'}, {'prev-word': 'त्यस', 'next-word': 'हुने', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'संसद', 'word': 'हुने'}, {'prev-word': 'हुने', 'next-word': 'को', 'word': 'संसद'}, {'prev-word': 'संसद', 'next-word': 'अधिवेशन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'तिर', 'word': 'अधिवेशन'}, {'prev-word': 'अधिवेशन', 'next-word': 'केन्द्रित', 'word': 'तिर'}, {'prev-word': 'तिर', 'next-word': 'हुन', 'word': 'केन्द्रित'}, {'prev-word': 'केन्द्रित', 'next-word': 'थाले', 'word': 'हुन'}, {'prev-word': 'हुन', 'next-word': 'को', 'word': 'थाले'}, {'prev-word': 'थाले', 'next-word': 'छ', 'word': 'को'}, {'prev-word': 'को', 'next-word': '।', 'word': 'छ'}, {'prev-word': 'छ', 'next-word': '', 'word': '।'}]
# List of corresponding labels
trainLabels = ['JX', 'NN', 'II', 'JX', 'NN', 'VE', 'IKM', 'NN', 'NN', 'IKM', 'JX', 'NN', 'IKO', 'NN', 'IKM', 'NN', 'II', 'NN', 'NP', 'NP', 'NP', 'IE', 'MM', 'JX', 'NN', 'NN', 'IKM', 'NN', 'VR', 'VI', 'VE', 'II', 'NN', 'IKM', 'NN', 'JX', 'NN', 'IKM', 'NN', 'CC', 'DDX', 'II', 'VN', 'NN', 'IKM', 'NN', 'II', 'JX', 'VI', 'VE', 'IKM', 'VVYN1', 'YF']

# Sample test data (features)
test_feat =[]   # List of feature dictionaries for test data
# List of words for test data
test = ['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा']
# test = [{'pos': 'IKM', 'prev-prev-word': 'अधिवेशन', 'word': 'को', 'prev-word': 'आषाढ', 'prev-pos': 'NN', 'next-next-word': 'मा', 'prev-prev-pos': 'NN', 'next-pos': 'NN', 'next-word': 'शुरु', 'nextnextpos': 'II'}]

# Loop to extract features from test data
for x in range(0, len(test)):
    test_feat.append(get_wordFeatures(test, x))
print(test, test_feat)


# Convert training and test features into Numpy arrays using DictVectorizer
vec = DictVectorizer(sparse=False)
X_arr = vec.fit_transform(trainFeatures)
print("Converting word features into Numpy arrays")
# with open("train.txt", "wb") as f:
#     np.savetxt(f, X_arr)
#     f.close()
print(X_arr)
XTest_arr = vec.fit_transform(test_feat)
print("Converting test word features into Numpy arrays")
# with open("test.txt", "wb") as f:
#     np.savetxt(f, XTest_arr)
#     f.close()
print(XTest_arr)


print(X_arr.shape[1], XTest_arr.shape[1])  # Print the dimensions of the feature arrays
clf = svm.SVC(kernel="linear")    # Create an SVM classifier with a linear kernel
clf.fit(X_arr, trainLabels)   # Train the SVM classifier on the training data

# Print support vectors and related information
print("Support vectors")
print(clf.support_vectors_)
with open("support.txt", "wb") as f:
    np.savetxt(f, clf.support_vectors_)
    f.close()
print("No of Support Vectors")
print(clf.n_support_)
print("Support vector indices")
print(clf.support_)


['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा'] [{'word': 'संसद', 'next-word': 'को', 'next-next-word': 'अधिवेशन', 'prev-word': '', 'prev-prev-word': ''}, {'word': 'को', 'next-word': 'अधिवेशन', 'next-next-word': 'आषाढ', 'prev-word': 'संसद', 'prev-prev-word': ''}, {'word': 'अधिवेशन', 'next-word': 'आषाढ', 'next-next-word': 'को', 'prev-word': 'को', 'prev-prev-word': 'संसद'}, {'word': 'आषाढ', 'next-word': 'को', 'next-next-word': 'शुरु', 'prev-word': 'अधिवेशन', 'prev-prev-word': 'को'}, {'word': 'को', 'next-word': 'शुरु', 'next-next-word': 'मा', 'prev-word': 'आषाढ', 'prev-prev-word': 'अधिवेशन'}, {'word': 'शुरु', 'next-word': 'मा', 'next-next-word': 'हुने', 'prev-word': 'को', 'prev-prev-word': 'आषाढ'}, {'word': 'मा', 'next-word': 'हुने', 'next-next-word': 'राष्ट्रियसभा', 'prev-word': 'शुरु', 'prev-prev-word': 'को'}, {'word': 'हुने', 'next-word': 'राष्ट्रियसभा', 'next-

This code seems to be focused on a classification task using an SVM model. It loads training data (features and labels), extracts features from test data, converts features into Numpy arrays, trains an SVM classifier, and prints information about the support vectors used in the trained model.

Please note that the actual functionality of the ExtractFeatures module is not provided in this code snippet, so you would need to have that module defined and available to properly run this script. Additionally, the code seems to have some unused variables (e.g., X, y, X_test, y_test, test_sen, train_sen) and commented-out sections that may have been used for debugging or previous iterations of the code.

# (TRK) Summerize form of above code

below code demonstrates a machine learning workflow for training a support vector machine (SVM) classifier using scikit-learn. The script includes steps for feature extraction, data preprocessing, model training, and support vector analysis.

In [15]:
x = []
test_feat = []  # List of dictionaries containing test features
test = ['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा']

# Loop to extract features from test data
for x in range(0, len(test)):
    test_feat.append(get_wordFeatures(test, x))

In [17]:
# test_feat

The parameter `sparse` ***controls whether the resulting matrix is stored in a sparse format or a dense format***. Here, `sparse=False` indicates matrix result in dense format.

`In a sparse matrix`, only the ***non-zero values are stored*** along with their indices, which can be more memory-efficient when dealing with large datasets with many zero values. On the other hand, a `dense matrix` ***stores all values in memory***, which can be more memory-intensive but can provide faster access to the data.

`DictVectorizer(sparse=False)` means feature matrix is in a dense format, where all feature values are explicitly stored in memory. This can be useful for smaller datasets or when you want to perform operations that benefit from a dense matrix representation.

If memory efficiency is a concern and you're working with a large dataset, you might consider using the default sparse representation by omitting the sparse parameter or setting it to True. This could help reduce memory usage, especially if your dataset has a lot of zero values in the feature matrix.

In [19]:
# Convert training and test features into Numpy arrays using DictVectorizer
vec = DictVectorizer(sparse=False)    # Creating a DictVectorizer instance:
X_arr = vec.fit_transform(trainFeatures)
XTest_arr = vec.transform(test_feat)     # NOTE: Use the same DictVectorizer instance fitted on the training data to transform test features. (By using .transform() instead of .fit_transform() for the test data, you ensure that the same vocabulary of feature names is used for both training and test data transformations. This helps maintain consistency in the representation of features.)

In [25]:
# X_arr

In [26]:
# XTest_arr

In [23]:
# Print the dimensions of the feature arrays
print(X_arr.shape[1], XTest_arr.shape[1])

129 129


1.
**Support vectors** are the data points (samples) from the training set that lie closest to the decision boundary of the SVM classifier. These points play a crucial role in defining the decision boundary and class separation.

`clf.support_vectors_` contains the actual support vectors that were identified during the training process of the SVM classifier clf. These support vectors are represented as rows in the `X_arr` array, where each row corresponds to a support vector in the original feature space.

2.


The `.n_support_` attribute is another attribute of the SVM classifier in scikit-learn that *provides information about the number of support vectors for each class in a multiclass SVM*.

In a binary classification problem, an SVM typically has two classes: positive (+1) and negative (-1). The `.n_support_` attribute returns a NumPy array that indicates the number of support vectors for each class. The first element of the array corresponds to the number of support vectors for the negative class, and the second element corresponds to the number of support vectors for the positive class.

3.


The `.support_` attribute is a property of the SVM classifier in scikit-learn that *provides the indices of the support vectors in the original training dataset*. These indices correspond to the positions of the support vectors in the array used for training the SVM model.


In [28]:
# Create an SVM classifier with a linear kernel
clf = svm.SVC(kernel="linear")

# Train the SVM classifier on the training data
clf.fit(X_arr, trainLabels)

# Print support vectors and related information
print("Support vectors")
print(clf.support_vectors_)     # Print support vectors and related information
print("No of Support Vectors")
print(clf.n_support_)       # Print the number of support vectors for each class
print("Support vector indices")
print(clf.support_)       # Print support vector indices

Support vectors
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]]
No of Support Vectors
[ 1  1  1  5  8  1  6  1 17  3  3  2  1  1  1  1]
Support vector indices
[39 40 21  2 16 31 41 46  6  9 14 26 33 37 44 50 12  0  3 10 23 35 47 22
  1  4  7  8 11 13 15 17 24 25 27 32 34 36 38 43 45 18 19 20  5 30 49 29
 48 42 28 51 52]


In [29]:
import os
import xml.etree.ElementTree as ET
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction import DictVectorizer
from sklearn import svm

# Set the path to a specific XML file
path = 'nnc_updated_ah/cs/a02.xml'

# Lists to store training data (features and labels) and test data (features)
X, y, X_test, y_test, test_sen, train_sen = [], [], [], [], [], []


# *****************************Sample training data (features) and labels***********************************************************
### List of dictionaries containing training features
trainFeatures = [{'prev-word': '', 'next-word': 'निर्वाचन', 'word': 'आम'}, {'prev-word': 'आम', 'next-word': 'मा', 'word': 'निर्वाचन'}, {'prev-word': 'निर्वाचन', 'next-word': 'स्पष्ट', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'बहुमत', 'word': 'स्पष्ट'}, {'prev-word': 'स्पष्ट', 'next-word': 'ल्याए', 'word': 'बहुमत'}, {'prev-word': 'बहुमत', 'next-word': 'को', 'word': 'ल्याए'}, {'prev-word': 'ल्याए', 'next-word': 'नेपाली', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'काँग्रेस', 'word': 'नेपाली'}, {'prev-word': 'नेपाली', 'next-word': 'को', 'word': 'काँग्रेस'}, {'prev-word': 'काँग्रेस', 'next-word': 'संसदीय', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'दल', 'word': 'संसदीय'}, {'prev-word': 'संसदीय', 'next-word': 'का', 'word': 'दल'}, {'prev-word': 'दल', 'next-word': 'नेता', 'word': 'का'}, {'prev-word': 'का', 'next-word': 'को', 'word': 'नेता'}, {'prev-word': 'नेता', 'next-word': 'रुप', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'मा', 'word': 'रुप'}, {'prev-word': 'रुप', 'next-word': 'श्री', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'गिरीजा', 'word': 'श्री'}, {'prev-word': 'श्री', 'next-word': 'प्रसाद', 'word': 'गिरीजा'}, {'prev-word': 'गिरीजा', 'next-word': 'कोइराला', 'word': 'प्रसाद'}, {'prev-word': 'प्रसाद', 'next-word': 'ले', 'word': 'कोइराला'}, {'prev-word': 'कोइराला', 'next-word': 'पन्द्रह', 'word': 'ले'}, {'prev-word': 'ले', 'next-word': 'सदस्यीय', 'word': 'पन्द्रह'}, {'prev-word': 'पन्द्रह', 'next-word': 'मन्त्रि', 'word': 'सदस्यीय'}, {'prev-word': 'सदस्यीय', 'next-word': 'परिषद', 'word': 'मन्त्रि'}, {'prev-word': 'मन्त्रि', 'next-word': 'को', 'word': 'परिषद'}, {'prev-word': 'परिषद', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'गरी', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'सक्नु', 'word': 'गरी'}, {'prev-word': 'गरी', 'next-word': 'भए', 'word': 'सक्नु'}, {'prev-word': 'सक्नु', 'next-word': 'पछि', 'word': 'भए'}, {'prev-word': 'भए', 'next-word': 'मुलुक', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'को', 'word': 'मुलुक'}, {'prev-word': 'मुलुक', 'next-word': 'ध्यान', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'राष्ट्रिय', 'word': 'ध्यान'}, {'prev-word': 'ध्यान', 'next-word': 'सभा', 'word': 'राष्ट्रिय'}, {'prev-word': 'राष्ट्रिय', 'next-word': 'को', 'word': 'सभा'}, {'prev-word': 'सभा', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'र', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'त्यस', 'word': 'र'}, {'prev-word': 'र', 'next-word': 'पछि', 'word': 'त्यस'}, {'prev-word': 'त्यस', 'next-word': 'हुने', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'संसद', 'word': 'हुने'}, {'prev-word': 'हुने', 'next-word': 'को', 'word': 'संसद'}, {'prev-word': 'संसद', 'next-word': 'अधिवेशन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'तिर', 'word': 'अधिवेशन'}, {'prev-word': 'अधिवेशन', 'next-word': 'केन्द्रित', 'word': 'तिर'}, {'prev-word': 'तिर', 'next-word': 'हुन', 'word': 'केन्द्रित'}, {'prev-word': 'केन्द्रित', 'next-word': 'थाले', 'word': 'हुन'}, {'prev-word': 'हुन', 'next-word': 'को', 'word': 'थाले'}, {'prev-word': 'थाले', 'next-word': 'छ', 'word': 'को'}, {'prev-word': 'को', 'next-word': '।', 'word': 'छ'}, {'prev-word': 'छ', 'next-word': '', 'word': '।'}]
### Corresponding labels for the training data
trainLabels = ['JX', 'NN', 'II', 'JX', 'NN', 'VE', 'IKM', 'NN', 'NN', 'IKM', 'JX', 'NN', 'IKO', 'NN', 'IKM', 'NN', 'II', 'NN', 'NP', 'NP', 'NP', 'IE', 'MM', 'JX', 'NN', 'NN', 'IKM', 'NN', 'VR', 'VI', 'VE', 'II', 'NN', 'IKM', 'NN', 'JX', 'NN', 'IKM', 'NN', 'CC', 'DDX', 'II', 'VN', 'NN', 'IKM', 'NN', 'II', 'JX', 'VI', 'VE', 'IKM', 'VVYN1', 'YF']


# *****************************Sample test data (features)****************************************************************************
test_feat = []  # List of dictionaries containing test features
### List of words for test data
test = ['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा']
# test = [{'pos': 'IKM', 'prev-prev-word': 'अधिवेशन', 'word': 'को', 'prev-word': 'आषाढ', 'prev-pos': 'NN', 'next-next-word': 'मा', 'prev-prev-pos': 'NN', 'next-pos': 'NN', 'next-word': 'शुरु', 'nextnextpos': 'II'}]



# Loop to extract features from test data
for x in range(0, len(test)):
    test_feat.append(get_wordFeatures(test, x))

# Convert training and test features into Numpy arrays using DictVectorizer
vec = DictVectorizer(sparse=False)    # instance of DictVectorizer
X_arr = vec.fit_transform(trainFeatures)
XTest_arr = vec.transform(test_feat)     # NOTE: Use the same DictVectorizer instance fitted on the training data to transform test features. (By using .transform() instead of .fit_transform() for the test data, you ensure that the same vocabulary of feature names is used for both training and test data transformations. This helps maintain consistency in the representation of features.)

# Print the dimensions of the feature arrays
print(X_arr.shape[1], XTest_arr.shape[1])

# Create an SVM classifier with a linear kernel
clf = svm.SVC(kernel="linear")

# Train the SVM classifier on the training data
clf.fit(X_arr, trainLabels)

# Print support vectors and related information
print("Support vectors")
print(clf.support_vectors_)
print("No of Support Vectors")
print(clf.n_support_)
print("Support vector indices")
print(clf.support_)


129 129
Support vectors
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]]
No of Support Vectors
[ 1  1  1  5  8  1  6  1 17  3  3  2  1  1  1  1]
Support vector indices
[39 40 21  2 16 31 41 46  6  9 14 26 33 37 44 50 12  0  3 10 23 35 47 22
  1  4  7  8 11 13 15 17 24 25 27 32 34 36 38 43 45 18 19 20  5 30 49 29
 48 42 28 51 52]


# 4. test.py

Accuracy: 86.15384615384616

In [30]:
import os
# import ExtractFeatures
import xml.etree.ElementTree as ET

path = 'nnc_updated_ah/cs/a01.xml'
# filelist = os.listdir(path)
# for file in filelist:
#     filepath = os.path.join(path, file)
#     print(filepath)

X, y, X_test, y_test, test_sen = [], [], [], [], []
temp = 0

tree = ET.parse(path)
root = tree.getroot()
single_sentence = []

for data in root.findall('text'):
            for value in data:
                # print(value.tag)
                if (value.tag == 'group'):
                    # for group in value.findall('group'):
                    for body in value.findall('body'):
                        for div in body.findall('div'):
                            for subdiv in div:
                                # print(subdiv.tag)
                                if (subdiv.tag == "head"):

                                    for sentence in subdiv.findall('s'):
                                        print(sentence.attrib)
                                        single_sentence = []
                                        for s in sentence:
                                            # print(s.attrib)
                                            if (s.tag == "foreign"):
                                                for words in s.findall('w'):
                                                    print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # print("\n")
                                            if (s.tag == "w"):
                                                # print("%s %s" % (s.text, s.attrib['ctag']), '', end=''),
                                                single_sentence.append(s.text)
                                                single_sentence.append(s.attrib['ctag'])
                                                test_sen.append(s.text)
                                                y_test.append(s.attrib['ctag'])
                                        print(single_sentence)

                                        for x in range(0, len(single_sentence), 2):
                                            # print(get_features(single_sentence,x))
                                            X_test.append(get_testfeatures(single_sentence, x))
                                #         # print('\n')
                                # print(len(single_sentence))
                                if (subdiv.tag == "p"):
                                    for sentence in subdiv.findall('s'):
                                        # print(sentence.attrib)
                                        single_sentence = []
                                        for s in sentence:
                                            if (s.tag == "foreign"):
                                                for words in s.findall('w'):
                                                  print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # print("\n")
                                            if (s.tag == "w"):
                                                temp = temp+1
                                                # print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                                single_sentence.append(s.text)
                                                single_sentence.append(s.attrib['ctag'])
                                                y.append(s.attrib['ctag'])

                                        for x in range(0, len(single_sentence), 2):
                                            X.append(get_testfeatures(single_sentence, x))
                                            # temp = temp + 1

    # print(temp)
print(len(X), len(X_test))
print(len(y), len(y_test))

from sklearn.feature_extraction import DictVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

clf = Pipeline([
            ('vectorizer', DictVectorizer(sparse=False)),
            ('classifier', LinearSVC())
        ])
clf.fit(X[:50],y[:50])

y_predict = (clf.predict(X_test))
print(test_sen)
print(y_predict)
accuracy = ((clf.score(X_test, y_test)) * 100)
print("Accuracy:", accuracy)

for x in range(0, len(test_sen)):
     print("%s/%s" % (test_sen[x], y_predict[x]),'', end='')

import pickle
pickle.dump(clf, open("RESULT.pickle", "wb"))


0 0
0 0


ValueError: ignored

# 5. pos-ui.py

 Serving Flask app for display the output in the urls page

In [ ]:
import pickle
from flask import Flask, render_template, request

app = Flask(__name__)
loadModel = pickle.load(open("RESULT.pickle", "rb"))


def assignTag(testFeatures):
    output = loadModel.predict(testFeatures)
    return output


def get_wordFeatures(tokens, index):
    word = tokens[index]
    if index == 0:
        prevword = ''
        prevprevword = ''
    elif index == 1:
        prevword = tokens[index - 1]
        prevprevword = ''
    else:
        prevword = tokens[index - 1]
        prevprevword = tokens[index - 2]

    if index == len(tokens) - 1:
        nextword = ''
        nextnextword = ''
    elif index == len(tokens) - 2:
        nextword = tokens[index + 1]
        nextnextword = ''
    else:
        nextword = tokens[index + 1]
        nextnextword = tokens[index + 2]

    return {
        'word': word,
        'next-word': nextword,
        'next-next-word': nextnextword,
        'prev-word': prevword,
        'prev-prev-word': prevprevword,
    }


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/predict', methods=['POST'])
def predict():
    testFeatures, token, tags, desc = [], [], [], []
    text = request.form['testSentence']
    i = len(text.split())
    splits = (text.split())
    for y in range(0, i):
        token.append(splits[y])
    for x in range(0, len(token)):
        testFeatures.append(get_wordFeatures(token, x))
    tags = assignTag(testFeatures)
    return render_template("predict.html", sen_pos=zip(token, tags))


if __name__ == '__main__':
    app.run(debug=True)
